AWSTemplateFormatVersion: "2010-09-09"

# Parameters:
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------# 
  # VPCCIDR:
  #   Default: 10.0.0.0/16
  #   Type: String

  # PublicSubnet01CIDR:
  #   Default: 10.0.0.0/24
  #   Type: String

  # PublicSubnet02CIDR:
  #   Default: 10.0.1.0/24
  #   Type: String

  # PrivateSubnet01CIDR:
  #   Default: 10.0.2.0/24
  #   Type: String

  # PrivateSubnet02CIDR:
  #   Default: 10.0.3.0/24
  #   Type: String

Resources:

# ------------------------------------------------------------#
# ALB
# ------------------------------------------------------------# 
  # ALB:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     IpAddressType: ipv4
  #     Name: alb
  #     Scheme: internet-facing
  #     SecurityGroups:
  #       - !Ref ALBSG
  #     Subnets: 
  #       - !Ref PublicSubnet01
  #       - !Ref PublicSubnet02
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-alb
  #     Type: application

  # TargetGroup:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     HealthCheckEnabled: true
  #     HealthCheckIntervalSeconds: 30
  #     HealthCheckPath: /
  #     HealthCheckPort: 80
  #     HealthCheckProtocol: HTTP
  #     HealthCheckTimeoutSeconds: 5
  #     HealthyThresholdCount: 5
  #     IpAddressType: ipv4
  #     Matcher:
  #       HttpCode: 200
  #     Name: ecs-test-tg
  #     Port: 80
  #     Protocol: HTTP
  #     ProtocolVersion: HTTP1
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-tg
  #     TargetType: ip
  #     UnhealthyThresholdCount: 2
  #     VpcId: !Ref VPC

  # ALBHTTPListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - TargetGroupArn: !Ref TargetGroup
  #         Type: forward
  #     LoadBalancerArn: !Ref ALB
  #     Port: 80
  #     Protocol: HTTP

# ------------------------------------------------------------#
# IAM
# ------------------------------------------------------------# 
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: ecs-test-tast-execution-role

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: ecs-test-tast-role

# ------------------------------------------------------------#
# ECR
# ------------------------------------------------------------# 
  # ECR:
  #   Type: AWS::ECR::Repository
  #   Properties:
  #     EmptyOnDelete: true
  #     EncryptionConfiguration:
  #       EncryptionType: AES256
  #     RepositoryName: sofi-app

# ------------------------------------------------------------#
# ECS
# ------------------------------------------------------------# 
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: sofi-app-cluster
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1

  ECSTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/sofi-app-cluster:latest
          # LogConfiguration:
          #   LogDriver: awslogs
          #   Options: 
          #     awslogs-group: "/ecs/logs/ecs-test-log"
          #     awslogs-region: !Ref "AWS::Region"
          #     awslogs-stream-prefix: "ecs-test-log"
          Name: sofi-app-task-define
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
      Cpu: 256
      ExecutionRoleArn: !Ref TaskExecutionRole
      Family: sofi-app-task-define
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref TaskRole

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - 'sg-0f1be97bb0725c14e'
          Subnets:
            - 'subnet-06d611194c004c12f'
            - 'subnet-0dac0c294c909f19c'
      ServiceName: sofi-app-service
      TaskDefinition: !Ref ECSTaskDef
