AWSTemplateFormatVersion: "2010-09-09"

# Parameters:
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------# 
  # VPCCIDR:
  #   Default: 10.0.0.0/16
  #   Type: String

  # PublicSubnet01CIDR:
  #   Default: 10.0.0.0/24
  #   Type: String

  # PublicSubnet02CIDR:
  #   Default: 10.0.1.0/24
  #   Type: String

  # PrivateSubnet01CIDR:
  #   Default: 10.0.2.0/24
  #   Type: String

  # PrivateSubnet02CIDR:
  #   Default: 10.0.3.0/24
  #   Type: String

Resources:
# ------------------------------------------------------------#
# VPC
# ------------------------------------------------------------# 
  # VPC:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: !Ref VPCCIDR
  #     EnableDnsSupport: true
  #     EnableDnsHostnames: true
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-vpc

# ------------------------------------------------------------#
# Subnet
# ------------------------------------------------------------# 
  # PublicSubnet01:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: ap-northeast-1a
  #     CidrBlock: !Ref PublicSubnet01CIDR
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-public-01
  #     VpcId: !Ref VPC

  # PublicSubnet02:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: ap-northeast-1c
  #     CidrBlock: !Ref PublicSubnet02CIDR
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-public-02
  #     VpcId: !Ref VPC

  # PrivateSubnet01:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: ap-northeast-1a
  #     CidrBlock: !Ref PrivateSubnet01CIDR
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-private-01
  #     VpcId: !Ref VPC

  # PrivateSubnet02:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone: ap-northeast-1c
  #     CidrBlock: !Ref PrivateSubnet02CIDR
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-private-02
  #     VpcId: !Ref VPC

# ------------------------------------------------------------#
# InternetGateway
# ------------------------------------------------------------# 
  # InternetGateway:
  #   Type: AWS::EC2::InternetGateway
  #   Properties:
  #     Tags: 
  #       - Key: Name
  #         Value: !Sub ecs-test-igw

  # InternetGatewayAttachment:
  #   Type: AWS::EC2::VPCGatewayAttachment
  #   Properties:
  #     InternetGatewayId: !Ref InternetGateway
  #     VpcId: !Ref VPC

# ------------------------------------------------------------#
# RouteTable
# ------------------------------------------------------------# 
  # PublicRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref VPC
  #     Tags:
  #       - Key: Name
  #         Value: ecs-test-public-rtb

  # PublicRouteTableRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     DestinationCidrBlock: 0.0.0.0/0
  #     GatewayId: !Ref InternetGateway
  #     RouteTableId: !Ref PublicRouteTable

  # PublicRtAssociation1:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PublicRouteTable
  #     SubnetId: !Ref PublicSubnet01

  # PublicRtAssociation2:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PublicRouteTable
  #     SubnetId: !Ref PublicSubnet02

  # PrivateRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref VPC
  #     Tags:
  #       - Key: Name
  #         Value: ecs-test-private-rtb

  # PrivateRtAssociation1:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable
  #     SubnetId: !Ref PrivateSubnet01

  # PrivateRtAssociation2:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable
  #     SubnetId: !Ref PrivateSubnet02

# ------------------------------------------------------------#
# Security Group
# ------------------------------------------------------------# 
  # ALBSG:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: for alb
  #     GroupName: ecs-test-sg-alb
  #     SecurityGroupIngress:
  #       - FromPort: 80
  #         IpProtocol: tcp
  #         CidrIp: 0.0.0.0/0
  #         ToPort: 80
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-sg-alb
  #     VpcId: !Ref VPC

  # ECSSG:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: for ecs
  #     GroupName: test-sg-ecs
  #     SecurityGroupIngress:
  #       - FromPort: 80
  #         IpProtocol: tcp
  #         SourceSecurityGroupId: !Ref ALBSG
  #         ToPort: 80
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-sg-ecs
  #     VpcId: !Ref VPC

  # VPCEndpointSG:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: for VPC Endpoint
  #     GroupName: ecs-test-vpc-endpoint-sg
  #     SecurityGroupEgress: 
  #       - CidrIp: 0.0.0.0/0
  #         FromPort: -1
  #         IpProtocol: -1
  #         ToPort: -1
  #     SecurityGroupIngress: 
  #       - SourceSecurityGroupId: !Ref ECSSG
  #         FromPort: 443
  #         IpProtocol: tcp
  #         ToPort: 443
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-vpc-endpoint-sg
  #     VpcId: !Ref VPC

# ------------------------------------------------------------#
# VPC Endpoint
# ------------------------------------------------------------# 
  # S3Endpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties: 
  #     RouteTableIds: 
  #       - !Ref PrivateRouteTable
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
  #     VpcEndpointType: Gateway
  #     VpcId: !Ref VPC

  # ECRdkrEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     VpcEndpointType: Interface
  #     PrivateDnsEnabled: true
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
  #     VpcId: !Ref VPC
  #     SubnetIds:
  #       - !Ref PrivateSubnet01
  #     SecurityGroupIds:
  #       - !Ref VPCEndpointSG

  # ECRapiEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     VpcEndpointType: Interface
  #     PrivateDnsEnabled: true
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
  #     VpcId: !Ref VPC
  #     SubnetIds:
  #       - !Ref PrivateSubnet01
  #     SecurityGroupIds:
  #       - !Ref VPCEndpointSG

  # LogsEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     VpcEndpointType: Interface
  #     PrivateDnsEnabled: true
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
  #     VpcId: !Ref VPC
  #     SubnetIds:
  #       - !Ref PrivateSubnet01
  #     SecurityGroupIds:
  #       - !Ref VPCEndpointSG

  # SsmMessagesEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     VpcEndpointType: Interface
  #     PrivateDnsEnabled: true
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
  #     VpcId: !Ref VPC
  #     SubnetIds:
  #       - !Ref PrivateSubnet01
  #     SecurityGroupIds:
  #       - !Ref VPCEndpointSG

# ------------------------------------------------------------#
# ALB
# ------------------------------------------------------------# 
  # ALB:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     IpAddressType: ipv4
  #     Name: alb
  #     Scheme: internet-facing
  #     SecurityGroups:
  #       - !Ref ALBSG
  #     Subnets: 
  #       - !Ref PublicSubnet01
  #       - !Ref PublicSubnet02
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-alb
  #     Type: application

  # TargetGroup:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     HealthCheckEnabled: true
  #     HealthCheckIntervalSeconds: 30
  #     HealthCheckPath: /
  #     HealthCheckPort: 80
  #     HealthCheckProtocol: HTTP
  #     HealthCheckTimeoutSeconds: 5
  #     HealthyThresholdCount: 5
  #     IpAddressType: ipv4
  #     Matcher:
  #       HttpCode: 200
  #     Name: ecs-test-tg
  #     Port: 80
  #     Protocol: HTTP
  #     ProtocolVersion: HTTP1
  #     Tags: 
  #       - Key: Name
  #         Value: ecs-test-tg
  #     TargetType: ip
  #     UnhealthyThresholdCount: 2
  #     VpcId: !Ref VPC

  # ALBHTTPListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - TargetGroupArn: !Ref TargetGroup
  #         Type: forward
  #     LoadBalancerArn: !Ref ALB
  #     Port: 80
  #     Protocol: HTTP

# ------------------------------------------------------------#
# ECR
# ------------------------------------------------------------# 
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: true
      EncryptionConfiguration:
        EncryptionType: AES256
      RepositoryName: sofi-app
